name: Send Contributors to Discord
on:
  push:
    branches:
      - main
    paths:
      - contributors.json # Only trigger on changes to this file

jobs:
  send-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch contributors.json
        run: |
          curl -O https://raw.githubusercontent.com/GNOME-Nepal/contributors/main/contributors.json

      - name: Debug Information
        run: |
          ls -la
          cat contributors.json

      - name: Send to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python send_to_discord.py
